spring.datasource.url=${DATABASE_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

alphavantage.api.key=${ALPHAVANTAGE_KEY:}

vatic.jwt.secret=${JWT_SECRET:}
vatic.jwt.expiration-ms=604800000